
server:
#    ssl:
#        key-store: classpath:config/tls/keystore.p12
#        key-store-password: password
#        key-store-type: PKCS12
#        key-alias: selfsigned
    ssl:
      key-store: https://take-out.oss-cn-hangzhou.aliyuncs.com/mycert.jks
      key-store-password: 51kUQS2I
      key-store-type: JKS
jhipster:
    http:
        version: V_2_0
